apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-72lz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-72lz@sha256:99327a0ad721943f500f3707be6ec9bc50d13149084f398a7e6ecde32e19d42e
        name: my-nodejs
        resources: {}
status: {}
